; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                              = 10210330-x86_64 Linux           
[ DataSettings ]
datatype                         = snNucleotide                    
containsCodingNuc                = False                           
MissingBaseSymbol                = ?                               
IdenticalBaseSymbol              = .                               
GapSymbol                        = -                               
Labelled Sites                   = All Sites                       
Labels to Include                =                                 
[ ProcessTypes ]
ppAnalyzeUserTree                = true                            
ppMP                             = true                            
ppCalcBlens                      = true                            
[ AnalysisSettings ]
Analysis                         = Analyze a User Tree             
Tree to Use                      = Use tree from file              
Max Relative Rate Ratio          = 20                              
Statistical Method               = Maximum Parsimony               
Substitution Model               = ====================            
Substitutions Type               = Nucleotide                      
Data Subset to Use               = ====================            
Gaps/Missing Data Treatment      = Complete deletion               
Site Coverage Cutoff (%)         = Not Applicable                  
Has Time Limit                   = False                           
Maximum Execution Time           = -1                              
