name: btb-forestry CI test

on: 
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!Dockerfile'

jobs:
  CI-testing:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Nextflow latest
        uses: nf-core/setup-nextflow@6c2e22b4d901f0c42ca66c5069f8026df026d165
        with:
          version: '25.04.8'
 
      - name: ECR Pull
        run: |
          docker pull defradigital/btb-forestry:latest

      - name: Set secrets
        run: |
          nextflow secrets set BRANCH "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run Tests
        run: nf-test test --ci
